In [1]:
import sys
import numpy as np

# Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

# Array Types

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype

dtype('float64')

In [18]:
np.array([1, 2, 3, 4], dtype=np.float)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8892\217965920.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4], dtype=np.float)


array([1., 2., 3., 4.])

In [19]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [20]:
c = np.array(['a', 'b', 'c'])

In [21]:
c.dtype

dtype('<U1')

In [22]:
d = np.array([{'a': 1}, sys])

In [23]:
d.dtype

dtype('O')

# Dimensions And Shapes

In [24]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [25]:
A.shape

(2, 3)

In [26]:
A.ndim

2

In [27]:
A.size

6

In [28]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [29]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [30]:
B.shape

(2, 2, 3)

In [31]:
B.ndim

3

In [32]:
B.size

12

In [33]:
# If the shape isn't consistent
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8892\2209047439.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [34]:
C.dtype

dtype('O')

In [35]:
C.shape

(2,)

In [36]:
C.size

2

In [37]:
type(C[0])

list

# Indexing and Slicing of Matrices

In [38]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [39]:
A[1]

array([4, 5, 6])

In [40]:
A[1][0]

4

In [41]:
A[1, 0]

4

In [42]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [44]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [45]:
A[:2, 2:]

array([[3],
       [6]])

In [46]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
A[1] = np.array([10, 10, 10])

In [48]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [49]:
A[2] = 99

In [50]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Summary Statistics

In [51]:
a = np.array([1, 2, 3, 4])

In [52]:
a.sum()

10

In [53]:
a.mean()

2.5

In [54]:
a.std()

1.118033988749895

In [55]:
a.var()

1.25

In [56]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [57]:
A.sum()

45

In [58]:
A.mean()

5.0

In [59]:
A.std()

2.581988897471611

In [60]:
A.sum(axis=0)

array([12, 15, 18])

In [61]:
A.sum(axis=1)

array([ 6, 15, 24])

In [62]:

A.mean(axis=0)

array([4., 5., 6.])

In [63]:
A.mean(axis=1)

array([2., 5., 8.])

In [64]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [65]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

Broadcasting and vectorized operations

In [66]:
a = np.arange(4)

In [67]:
a

array([0, 1, 2, 3])

In [68]:
a+10

array([10, 11, 12, 13])

In [69]:
and many more....

SyntaxError: invalid syntax (3434846678.py, line 1)

Boolean arrays

In [70]:
a = np.arange(4)

In [71]:
a

array([0, 1, 2, 3])

In [72]:
a[0], a[-1]

(0, 3)

In [73]:
a[[0, -1]]

array([0, 3])

In [74]:
a[[True, False, False, True]]

array([0, 3])

In [75]:
a

array([0, 1, 2, 3])

In [76]:
a >= 2

array([False, False,  True,  True])

In [77]:
a[a >= 2]

array([2, 3])

In [78]:
a.mean()

1.5

In [79]:
a[a > a.mean()]

array([2, 3])

In [80]:

a[~(a > a.mean())]

array([0, 1])

In [81]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [82]:

a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [83]:
A = np.random.randint(100, size=(3, 3))

In [84]:
A

array([[ 5, 66,  5],
       [30, 91, 35],
       [51, 40,  7]])

In [85]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([ 5,  5, 91, 51,  7])

In [86]:

A > 30

array([[False,  True, False],
       [False,  True,  True],
       [ True,  True, False]])

In [87]:
A[A > 30]

array([66, 91, 35, 51, 40])

Linear Algebra

In [88]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [89]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [90]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [91]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [92]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [93]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Size of objects in memory

In [95]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [96]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [97]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [98]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [99]:
np.dtype(float).itemsize

8

Lists are even larger

In [100]:
# A one-element list
sys.getsizeof([1])

64

In [101]:
# An array of one element in numpy
np.array([1]).nbytes

4

And performance is also important

In [102]:
l = list(range(100000))

In [103]:
a = np.arange(100000)

In [104]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 0 ns


216474736

In [105]:
%time sum([x ** 2 for x in l])

CPU times: total: 31.2 ms
Wall time: 29.8 ms


333328333350000

Useful Numpy Functions

In [ ]:
# Random
np.random.random(size=2)
np.random.normal(size=2)
np.random.rand(2, 4)

# Arange
np.arange(10)
np.arange(5, 10)
np.arange(0, 1, .1)

# Reshape
np.arange(10).reshape(2, 5)
np.arange(10).reshape(5, 2)

# Linspace
np.linspace(0, 1, 5)
np.linspace(0, 1, 20)
np.linspace(0, 1, 20, False)

# Zeros, ones, empty
np.zeros(5)
np.zeros((3, 3))
np.zeros((3, 3), dtype=np.int)
np.ones(5)
np.ones((3, 3))
np.empty(5)
np.empty((2, 2))

# Identity and eye
np.identity(3)
np.eye(3, 3)
np.eye(8, 4)
np.eye(8, 4, k=1)
np.eye(8, 4, k=-3)
"Hello World"[6]